name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to dockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        uses: docker/build-push-action@v3
        with:
          context: ./frontend/
          push: true
          tags: aayush786/django-helloworld-frontend:latest

  backend-build:
    runs-on: ubuntu-latest
    needs: frontend-build
    steps:
      - name: Cloning the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to duckerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v3
        with:
          context: ./backend/
          push: true
          tags: aayush786/django-helloworld-backend:latest
  
  deployment:
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - uses: sudosubin/git-clone-action@v1
        with:
          repository: 'aayush786-21/-django-next-js-postgres-deployment'
          platform: 'github'
      -
        name: Deploying in the orbstack vm using docker-compose file
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST_IP}}
          username: ${{ secrets.ORBSTACK_USERNAME}}
          ssh_key: ${{ secrets.SSH_KEY}}
          script:
            docker pull aayush786/django-helloworld-backend:latest
            docker pull aayush786/django-helloworld-frontend:latest
            docker compose -f .docker-compose.yml up -d
